# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee06cbd92a06fcc9d18cb47297dd870706e5451971089a0bb73c6c90a8059cc30bf224417b2b00d9351eab2b5140b6222baa75d2cf8dd627b79b40883ab66d4a

test:
  secret_key_base: e67f6692edbf9887c7460ac81a5f595ce9e8bdb0f112acbd7f356ebe750e8d1157f2b7888e3032a19037d34f98e3935e09ad5f0c4b4a0a4c943025901172b342

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
